keyboard:
  main-menu:
    "[–ò–≥—Ä–∞—Ç—å üéÆ]": /play
    "[–°—Ç–∞—Ç–∏—Å—Ç–∏–∫–∞ üìä]": /stat
    "[–¢–∞–±–ª–∏—Ü–∞ –ª–∏–¥–µ—Ä–æ–≤ ü•á]": /leaders
    "[–ò–Ω—Ñ–æ—Ä–º–∞—Ü–∏—è ‚ÅâÔ∏è]": /info
    "[–ê–¥–º–∏–Ω –ø–∞–Ω–µ–ª—å üëÆ‚Äç‚ôÇÔ∏èÔ∏è]": /admin
  option-menu:
    option1:
      text: "A. "
      callbackData: "/option1"
    option2:
      text: "B. "
      callbackData: "/option2"
    option3:
      text: "C. "
      callbackData: "/option3"
    option4:
      text: "D. "
      callbackData: "/option4"
  help-menu:
    help1:
      text: "50/50"
      callbackData: "/help1"
    help2:
      text: "–ü–æ–º–æ—â—å –∑–∞–ª–∞"
      callbackData: "/help2"
    help3:
      text: "–ó–≤–æ–Ω–æ–∫ –¥—Ä—É–≥—É"
      callbackData: "/help3"